fizbuzzWeb/Models/Fizbuzz.cs
namespace FizbuzzWeb.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Fizbuzz
    {
        [Display(Name = "Enter a number")]
        [Required(ErrorMessage = "*Enter a valid number")]
        [Range(1, 1000, ErrorMessage = "Enter the number between 1 and 1000")]
        public int InputNumer { get; set; }

        public List<string> DisplayList { get; set; }
    }
}

fizbuzzWeb/Controllers/FizbuzzController.cs
namespace FizbuzzWeb.Controllers
{
    using System.Web.Mvc;
    using FizBuzzLogic.Interface;
    using FizbuzzWeb.Models;

    public class FizbuzzController : Controller
    {
        private readonly ILogic fizbuzzLogic;

        public FizbuzzController(ILogic logic)
        {
            this.fizbuzzLogic = logic;
        }

        // GET: Fizbuzz
        [HttpGet]
        public ActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public ActionResult Index(Fizbuzz model)
        {
            if (this.ModelState.IsValid)
            {
                model.DisplayList = this.fizbuzzLogic.getList(model.InputNumer);
            }

            return this.View(model);
        }
    }
}

fizbuzzWeb/Views/Fizbuzz/Index.cshtml
@model FizbuzzWeb.Models.Fizbuzz

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("Index","Fizbuzz",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Fizbuzz</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.InputNumer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InputNumer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InputNumer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (Model != null && Model.DisplayList != null)
{
    <div class="container">
        <ul>
            @foreach (var item in Model.DisplayList)
            {
                <li>@item</li>
            }
        </ul>
    </div>
}

fizbuzzWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>